# Generated by Django 5.2.4 on 2025-07-05 08:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HRDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the document", max_length=255),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full document text (used for AI search)"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Upload time of the document",
                    ),
                ),
            ],
        ),
    ]
